# Generated by Django 2.0.5 on 2018-11-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_quality', '0001_initial'),
        ('user_quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requeststatus', models.CharField(default='pending', max_length=500)),
                ('quality', models.ForeignKey(on_delete='cascade', to='admin_quality.Upload_Model')),
                ('userId', models.ForeignKey(on_delete='cascade', to='user_quality.RegistrationModel')),
            ],
        ),
    ]
