# Generated by Django 2.0.5 on 2018-11-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_quality', '0002_userrequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqstatus', models.CharField(default='pending', max_length=100)),
                ('regid', models.ForeignKey(on_delete='cascade', to='user_quality.RegistrationModel')),
                ('reqid', models.ForeignKey(on_delete='cascade', to='user_quality.UserRequestmodel')),
            ],
        ),
    ]
