# Generated by Django 2.0.5 on 2018-11-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_quality', '0003_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='phoneno',
            field=models.CharField(max_length=100),
        ),
    ]
