# Generated by Django 2.0.5 on 2018-11-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_quality', '0004_auto_20181129_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='reqid',
            field=models.ForeignKey(on_delete='cascade', to='admin_quality.Upload_Model'),
        ),
    ]
